### ISSUE TITLE
Responsive and another info

### ISSUE THREAD

**Issue by genocide87** [miniclip/wp-miniclip-games#1]
Hello!

I'm trying this plugin, but I've a lot of trouble with the pop-up... there's an option to set a MAX-WIDTH and MAX-HEIGHT for responsive purpose?

And, I can pick a lot of games, but some of them are not centered into the pop-up. There's a way to center it?

Best Regards

**Comment by paulo-ferraz-oliveira** [comment]
Closing this as it's stale.
